server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: etudiant-service-etudiants
          uri: lb://etudiant-service
          predicates:
            - Path=/api/etudiants/**
        - id: etudiant-service-departements
          uri: lb://etudiant-service
          predicates:
            - Path=/api/departements/**
        - id: grading-service
          uri: lb://grading-service
          predicates:
            - Path=/api/notes/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: false
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
